hf_configuration:
  concat_if_exist: true
  hf_dataset_name: SVdriving
  hf_organization: null
  local_dataset_dir: ./my_test/output_dir
  local_saving: true
  private: true
  token: $HF_TOKEN
language_of_interest: English
model_list:
- api_key: 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
  base_url: https://integrate.api.nvidia.com/v1
  model_name: qwen/qwen3-235b-a22b
  provider: null
- api_key: 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
  base_url: https://integrate.api.nvidia.com/v1
  max_concurrent_requests: 1
  model_name: nvidia/llama-3.3-nemotron-super-49b-v1
  provider: null
- api_key: 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
  base_url: https://integrate.api.nvidia.com/v1
  max_concurrent_requests: 2
  model_name: nvidia/llama-3.3-nemotron-super-49b-v1
  provider: null
- api_key: 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
  base_url: https://integrate.api.nvidia.com/v1
  model_name: nvidia/llama-3.3-nemotron-super-49b-v1
  provider: null
model_roles:
  chunking:
  - intfloat/multilingual-e5-large-instruct
  ingestion:
  - qwen/qwen3-235b-a22b
  multi_hop_question_generation:
  - nvidia/llama-3.3-nemotron-super-49b-v1
  single_shot_question_generation:
  - nvidia/llama-3.3-nemotron-super-49b-v1
  summarization:
  - nvidia/llama-3.3-nemotron-super-49b-v1
pipeline:
  chunking:
    chunking_configuration:
      chunking_mode: semantic_chunking
      encoding_name: cl100k_base
      h_max: 10
      h_min: 5
      l_max_tokens: 128
      l_min_tokens: 64
      num_multihops_factor: 10
      tau_threshold: 0.8
      token_overlap: 0
    run: true
  citation_score_filtering:
    run: true
  ingestion:
    output_dir: ./my_test/processed
    run: true
    source_documents_dir: /workspace/test_upload/
  lighteval:
    run: false
  multi_hop_question_generation:
    chunk_sampling:
      mode: percentage
      random_seed: 42
      value: 0.3
    question_type: multi-choice
    run: false
  single_shot_question_generation:
    chunk_sampling:
      mode: count
      random_seed: 123
      value: 5
    question_type: multi-choice
    run: true
  summarization:
    encoding_name: cl100k_base
    max_tokens: 16384
    run: true
    token_overlap: 128
  upload_ingest_to_hub:
    run: true
    source_documents_dir: ./my_test/processed
